### ISSUE TITLE
Node Crash

### ISSUE THREAD

**Issue by dax0** [bitwalker/swarm#2]
Great library! Exactly what I was going to build myself but thankfully I didn't have to.  I've been testing out certain scenarios to see if it's appropriate for my use case.  Currently I'm testing with two nodes on my local machine, when I kill one the started processes don't seem to transfer over.  Calls to the process fail with no connection to node@localhost. When I restart the crashed node everything seems to fine

Is there something I'm missing? Thanks

**Comment by dax0** [comment]
Never mind I was using an old version from the docs that was way outdated.  All good on latest

**Comment by dax0** [comment]
Enabled debugging and I see this message `16:05:40.970 [debug] (swarm) cannot handoff, restarting` however it seems the process is not actually restarted.

**Comment by bitwalker** [comment]
Sorry @dax0, I've been on the road the past two days. I'll take a look ASAP!

**Comment by dax0** [comment]
Thanks!

**Comment by almightycouch** [comment]
Same here. 

```elixir
iex(916324837a68@916324837a68)1> Bleve.register_worker "foo"
12:51:47.863 [debug] (swarm) tracking name "foo"
{:ok, #PID<14532.163.0>}

iex(916324837a68@916324837a68)2> 
12:52:00.422 [debug] (swarm) nodedown: :"4847e97e5d69@4847e97e5d69"
12:52:00.422 [debug] (swarm) redistributing across [:"916324837a68@916324837a68"]
12:52:00.502 [debug] (swarm) cannot handoff, restarting "foo"
12:52:00.503 [debug] (swarm) synchronizing with [:"916324837a68@916324837a68"]
12:52:00.503 [debug] (swarm) synchronized with :"916324837a68@916324837a68"

iex(916324837a68@916324837a68)3> pid = Swarm.whereis_name "foo"
#PID<14532.163.0>

iex(916324837a68@916324837a68)4> :sys.get_status pid
** (exit) exited in: :sys.get_status(#PID<14532.163.0>)
    ** (EXIT) no connection to 4847e97e5d69@4847e97e5d69
    (stdlib) sys.erl:303: :sys.send_system_msg/2
```

Beyond this error, the library works really great! 👏 👏 👏 
I've started a swarm of ~10-20 nodes with docker (starting each container manually), everything (but the above problem) worked as excepted including redistribution and handoffs.

Here's the `Dockerfile` is use for my project in case you want to try out:

```Dockerfile
# 1) git archive -o bleve.tar.gz HEAD
# 2) docker network create elixir
# 3) docker build -t bleve .
# 4) docker run -it --net elixir --rm bleve

FROM elixir
RUN mkdir /app
WORKDIR /app
ADD bleve.tar.gz .
RUN mix local.hex --force
RUN mix deps.get
RUN mix compile
CMD iex --sname $(hostname) --cookie monster -S mix
```

**Comment by dax0** [comment]
Any updates on this?

**Comment by bitwalker** [comment]
Looking into this today, I'll report back with my findings.

**Comment by bitwalker** [comment]
Hey guys, just an update, I've been working on some largish changes to the internals all day, and this issue is one that should be resolved by them. I will update here as soon as I have a production-ready branch/release available, should be very soon!

**Comment by bitwalker** [comment]
@dax0 @almightycouch I'm getting ready to merge my changes into master and release them, but would like to have you guys test in your environments first before I do so. Could you swap out your dependency with `{:swarm, github: "bitwalker/swarm", branch: "pubsub"}` and give it a shot? If you have any problems with it please report them as new issues so I can track them separately, but I think it should be much more stable now.

Just as an FYI there are some knobs to tweak which I haven't documented yet, but I'll wait to see how the defaults do first. Also, the `autojoin` config setting is no longer present, and neither is `Swarm.join!` for manually joining the cluster. Other than that, it should be a drop-in replacement.

**Comment by dax0** [comment]
Will give this a shot tonight, thanks!

**Comment by dax0** [comment]
Still seeing the same issue.  If I start two nodes and then take down one of them, the processes aren't restarted on the surviving node.

**Comment by dax0** [comment]
![2016-09-11-221617_560x133_scrot](https://cloud.githubusercontent.com/assets/826656/18422832/66529d0e-786d-11e6-9aab-26dd64c12d91.png)

**Comment by bitwalker** [comment]
@dax0 I have unit tests which verify that they do get restarted, could you push a repo which I can use to reproduce and fix the issue?

I just pushed a fix for the `register_name` issue :)

**Comment by dax0** [comment]
I'm now seeing: `** (UndefinedFunctionError) function Swarm.Tracker.whereis/1 is undefined (module Swarm.Tracker is not available)`

**Comment by bitwalker** [comment]
Oops, should be fixed now!

**Comment by almightycouch** [comment]
> Still seeing the same issue. If I start two nodes and then take down one of them, the processes aren't restarted on the surviving node.

Same here. Using the `pubsub` branch.

Note that I'm starting my nodes directly with

```bash
iex --sname $(hostname) --cookie monster -S mix
```
Instead of turning a non-distributed node into a distributed node via `Node.start/3`.

When I start my IEx session in non-distributed mode and use `Node.start/3`, `Node.set_cookie/2` and `Node.ping/1` to turn it into a distributed node and join the cluster, `Node.stop/0` will shutdown the node correctly and restart my agents across the cluster (like your unit-test):

```elixir
iex(n1@macbook-pro)4> Node.stop
:ok

12:57:08.307 [debug] (swarm on nonode@nohost) node removed from ring: n2@macbook-pro
12:57:08.311 [debug] (swarm on nonode@nohost) node removed from ring: n1@macbook-pro
12:57:08.311 [debug] (swarm on nonode@nohost) restarting "foo" on nonode@nohost: connection to previous node n1@macbook-pro was lost
12:57:08.311 [debug] shutting down #PID<0.183.0>
12:57:08.311 [debug] (swarm on nonode@nohost) restarting "foo" on nonode@nohost: connection to previous node n1@macbook-pro was lost
12:57:08.311 [debug] (swarm on nonode@nohost) duplicate registration for "foo" (#PID<0.190.0>), resolving..
12:57:08.311 [debug] shutting down #PID<0.190.0>
```

But this is not the case when I

* kill the agent

    ```elixir
    Swarm.where_is_name("foo") |> Process.exit(:kill)
    ```
* kill the BEAM process (closing terminal for example).

* cause a network partition.

I've uploaded a small application example: [`:bleve`](https://github.com/almightycouch/bleve). To reproduce you can clone the repository and follow the steps in the `Dockerfile`.

1) Build the image and start a few containers with:

```bash
docker run -it --net elixir --rm bleve
```

2) On one node, register the alphabet:

```elixir
Bleve.register_alphabet
```

3) Make some topology changes (killing and starting Docker instances for example)

4) On one node, check the alphabet:

```elixir
reg = Bleve.register_alphabet
length reg # should be 26
```

**Comment by bitwalker** [comment]
Thanks so much for the detailed feedback!

I do want to point out that Swarm will make no attempt to restart processes if they exit themselves, or are killed by another process, they are only restarted if they need to be moved (due to cluster topology changes), or restarted (due to network partitions or cluster topology changes where nodes are removed from the cluster). So that part of it is working as expected.

I am surprised that processes aren't being restarted due to network partitions, as that's precisely what the current test simulates. Perhaps they are being killed after being restarted? It may be worth while to add logging to the `start_link` and `terminate` callbacks for the processes you are managing via Swarm to see how things are converging (I did that in my tests when I'm checking things out, and it's definitely helpful).

If nodes go down uncleanly, then it may take some time for Erlang's distribution to recognize that the node is no longer available and broadcast the `nodedown` event, I'm not sure what that timeout value is by default.

I'm exploring some other approaches now, as I'm not satisfied with the performance of the pubsub branch, it just seems like `phoenix_pubsub` is not intended for this particular use case, I basically have to hack around the `Phoenix.Tracker` API to prevent timeouts when registering thousands of processes and then partitioning/healing the network, due to the flood of events, and I can't get the nodes to converge remotely fast enough for my needs after re-joining the partitions. However the branch did give me some good ideas that I'm carrying forward, so bear with me while I sort out the kinks!

**Comment by almightycouch** [comment]
> I do want to point out that Swarm will make no attempt to restart processes if they exit themselves, or are killed by another process, they are only restarted if they need to be moved (due to cluster topology changes), or restarted (due to network partitions or cluster topology changes where nodes are removed from the cluster). So that part of it is working as expected.

Yes, it makes sense. Is there a way to gracefully leave the cluster and force handoffs before the node goes down? If I understand correctly, handoffs only occur when a new node joins the cluster and not the other way around.

> If nodes go down uncleanly, then it may take some time for Erlang's distribution to recognize that the node is no longer available and broadcast the nodedown event, I'm not sure what that timeout value is by default.

I found out that shutting down a node with `System.halt/0` works properly, redistributing the processes across the ring:

```elixir
18:40:46.200 [debug] (swarm on bd98f542121e@bd98f542121e) node removed from ring: d0c38c3b5aec@d0c38c3b5aec
18:40:46.203 [debug] (swarm on bd98f542121e@bd98f542121e) restarting "a" on bd98f542121e@bd98f542121e: connection to previous node d0c38c3b5aec@d0c38c3b5aec was lost
18:40:46.204 [debug] (swarm on bd98f542121e@bd98f542121e) restarting "f" on bd98f542121e@bd98f542121e: connection to previous node d0c38c3b5aec@d0c38c3b5aec was lost
18:40:46.204 [debug] (swarm on bd98f542121e@bd98f542121e) restarting "g" on bd98f542121e@bd98f542121e: connection to previous node d0c38c3b5aec@d0c38c3b5aec was lost
18:40:46.204 [debug] (swarm on bd98f542121e@bd98f542121e) restarting "h" on bd98f542121e@bd98f542121e: connection to previous node d0c38c3b5aec@d0c38c3b5aec was lost
...
```

When shutting down a node uncleanly (using `^C^C` from IEx for example), it looks like the `Swarm.Ring` is detecting the node going down almost instantly:

```elixir
8:30:52.999 [debug] (swarm on 3d9f66130dff@3d9f66130dff) node removed from ring: d43a8500c8b5@d43a8500c8b5
```

But `Swarm.Registry.redistribute!/0` does not restart the processes correctly.

**Comment by bitwalker** [comment]
I'm getting close to having a new implementation of the registry/tracker completed which should do a better job of this. I've literally re-written Swarm like 4 times now trying different approaches haha. It's tough to find the best way to do all of the following:

- is multi-master
- supports dynamic cluster membership
- is fast
- is (eventually) consistent in a way that's useful, in other words, you'd expect all nodes in the cluster to converge on a correct view of the registry in as short a time as possible, the longer it takes, the less useful it is
- resolves conflicts correctly/intuitively
- only require moving a small subset of processes when cluster topology changes

The initial version of Swarm works, albeit with some bugs, but it is a naive approach that is not correct. The version built on `phoenix_pubsub` was too slow, and didn't have a great mechanism for resolving conflicts. I built a version on `mnesia`, but it can't support dynamic cluster membership, so that was abandoned. The version I'm building now is based on a push-based, log-transfer optimistic replication algorithm with interval tree clocks as the conflict resolution data structure, and should be a balance between all of the points above, but it remains to be seen how fast it will be - I'm finishing it up today, so we'll see.

Sorry about the churn, but I'm using this in production and I want it to be correct (and useful), so I'm iterating until I find the right combination of tools to solve the problem.

**Comment by bitwalker** [comment]
I've pushed my latest work to the `rewrite` branch. It's missing process groups at the moment, and there are a few edge cases around conflict resolution I need to polish up (though to hit them would be rare indeed), but I'd love to hear how it works for you. If things are looking good for other people, I'll tie up the loose ends and push a new release.

**Comment by almightycouch** [comment]
After playing around with it for a while, the latest implementation seems really impressive 😍.
Well done! The logs are very explicit and helpful to understand what's going on.

On my machine, processes are successfully restarted when a Node goes down.

**Comment by bitwalker** [comment]
@almightycouch Thanks for the feedback! It's great to hear it's working for more than just my projects :). Just FYI, I cut a new release with the latest implementation, 1.0, in case you are pointing at master or another branch.

I'm looking into some other improvements at the moment as well. Namely a better way to handle supervised tasks which are registered via Swarm, but can still be shifted/restarted based on cluster topology changes. This would be implemented via a new supervisor module, where one defines a child specification, like you would with `:simple_one_for_one` supervisors, then you start children with `Swarm.Supervisor.start_child`, and Swarm will pass ownership of that process back to that supervisor after it's started, leaving restarts up to the supervisor to execute, based on the child specification. 

Today, if you start a child via a supervisor, you should set it's restart type to `:temporary` to prevent issues with Swarm - for example, if the process dies unexpectedly, it will be restarted by the supervisor, but it will no longer be registered via Swarm. Swarm itself could in theory supervise processes it starts, but I think it's more ergonomic to have a normal supervisor definition that feels familiar.

P.S. If you want an even more detailed view into the running Swarm process, run `:sys.trace(Swarm.Tracker)` ;)

**Comment by bitwalker** [comment]
FYI, I'm going to close this issue for now, as it should have been resolved in the latest release. If it reoccurs, please open a new issue so I can track it separately :)
